links/urls.py
""" URLConf """


from django.urls import path
from links import views


app_name = 'links'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('links/', views.URLListView.as_view(), name='url_list'),
    path('links/new/', views.URLCreateView.as_view(), name='create_url'),
    path('links/<int:id>/', views.URLDetailView.as_view(), name='url_detail'),
    path('links/<int:id>/update/', views.URLUpdateView.as_view(), name='update_url'),
    path('links/<int:id>/delete/', views.URLDeleteView.as_view(), name='delete_url'),
    path('<slug:slug>/', views.ServeURL.as_view(), name='redirect'),
]

links/models.py
""" Data Models """


from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


# Create your models here.
class URL(models.Model):
    """ URLs """

    # The owner of shortened url
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        help_text='The owner'
    )
    url = models.URLField(
        unique=True,
        db_index=True,
        help_text='The link to be shortened'
    )
    token = models.CharField(
        max_length=10,
        unique=True,
        db_index=True,
        help_text='Link token'
    )
    clicks = models.BigIntegerField(default=0)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.url

links/views.py
""" Views """


import secrets
from typing import Any

from django.conf import settings
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.forms.forms import BaseForm
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from links.models import URL
from links.mixins import UserFilterMixin


# Create your views here.
class Index(generic.TemplateView):
    """ Index page """

    template_name = 'links/index.html'


class URLCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    """ URL CreateView """

    model = URL
    fields = ['url']
    template_name = "links/create.html"
    success_url = reverse_lazy('links:url_list')
    success_message = 'Link was created successfully'

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        """ Redirect to details or create new instance """

        try:
            url = URL.objects.get(url=request.POST['url'])
            return redirect(reverse_lazy('links:url_detail', args=[url.pk]))

        except URL.DoesNotExist:
            return super().post(request, *args, **kwargs)

    def form_valid(self, form: BaseForm) -> HttpResponse:
        """ Compute the shortened url """

        # Create a url object
        instance: URL = form.save(commit=False)

        # Set the owner and url token
        instance.user = self.request.user
        instance.token = secrets.token_urlsafe(7)

        # Save the object
        instance.save()
        return super().form_valid(form)


class URLListView(LoginRequiredMixin, UserFilterMixin, generic.ListView):
    """ URL List view """

    model = URL
    template_name = 'links/list.html'
    extra_context = {'site_url': settings.LINKS_SITE_URL}


class URLDetailView(LoginRequiredMixin, UserFilterMixin, generic.DetailView):
    """ URL Details """

    model = URL
    pk_url_kwarg = 'id'
    template_name = 'links/detail.html'
    extra_context = {'site_url': settings.LINKS_SITE_URL}


class URLUpdateView(LoginRequiredMixin, UserFilterMixin, SuccessMessageMixin, generic.UpdateView):
    """ URL Update View """

    model = URL
    pk_url_kwarg = 'id'
    fields = ['token', 'url']
    template_name = 'links/update.html'
    success_url = reverse_lazy('links:url_list')
    success_message = 'Link was updated successfully'


class URLDeleteView(LoginRequiredMixin, UserFilterMixin, SuccessMessageMixin, generic.DeleteView):
    """ URL Delete View """

    model = URL
    pk_url_kwarg = 'id'
    template_name = 'links/delete.html'
    success_url = reverse_lazy('links:url_list')
    success_message = 'Link was deleted successfully'


class ServeURL(generic.DetailView):
    """ Redirect URLs """

    model = URL
    slug_field = 'token'

    def get(self, request, *args, **kwargs):
        """ Redirect urls """

        instance = self.get_object()
        instance.clicks += 1
        instance.save()

        return redirect(instance.url)

links/templates/links/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@latest/font/bootstrap-icons.css" />
  <title>{% block title %}{% endblock %}</title>
</head>

<body {% block body_attrs %}{% endblock %}>
  <header>{% block header %}{% endblock %}</header>
  <main>{% block main %}{% endblock %}</main>
  <footer>{% block footer %}{% endblock %}</footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
</body>

</html>

links/templates/links/components/delete-modal.html
{% load i18n %}
<div class="modal fade" id="deleteModal" data-bs-backdrop="static" data-bs-keyword="false" tabindex="-1"
  aria-labelledby="deleteModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content p-4 rounded-4 bg-light">
      <div class="modal-header flex-row card card-body rounded-4 mb-4 p-4 border-0">
        <h3 class="modal-title" id="deleteModalTitle">
          {% translate 'Delete Link' %}
        </h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body card card-body p-4 rounded-4 border-0">
        <p class="lead mb-4">
          {% translate 'Are you sure you want to delete this link?' %}
        </p>
        <form id="deleteForm" action="{% url 'links:delete_url' 0 %}" data-last-id="0" method="post">
          {% csrf_token %}
          <div class="d-flex flex-column flex-lg-row align-items-center gap-4">
            <button type="submit" class="btn btn-lg btn-danger w-100 shadow-sm rounded-3 fw-bold">
              {% translate 'Delete' %}
            </button>
            <button type="button" class="btn btn-lg btn-light w-100 shadow-sm rounded-3 fw-bold"
              data-bs-dismiss="modal">
              {% translate 'Close' %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

links/templates/links/components/messages.html
<ul class="list-unstyled mb-0">
  {% for message in messages %}
  <li class="alert alert-{{ message.tags }} d-flex align-items-center p-4 gap-4 shadow-sm rounded-4 alert-dismissible">
    <span class="badge bg-{{ message.tags }}">{{ message.tags|capfirst }}</span>
    {{ message }}
    <button type="button" class="btn-close rounded-4" data-bs-dismiss="alert" aria-label="Close"></button>
  </li>
  {% endfor %}
</ul>

links/templates/links/components/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-white rounded-4 m-2 p-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'links:index' %}">
      <strong>{% translate 'Links' %}</strong>
    </a>
    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbar"
      aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link d-flex align-items-center gap-4 gap-lg-2" href="{% url 'links:index' %}">
            <i class="bi bi-house"></i>
            {% translate 'Home' %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link d-flex align-items-center gap-4 gap-lg-2" href="{% url 'links:url_list' %}">
            <i class="bi bi-link-45deg"></i>
            {% translate 'My Links' %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link d-flex align-items-center gap-4 gap-lg-2" href="{% url 'links:create_url' %}">
            <i class="bi bi-plus-lg"></i>
            {% translate 'New Link' %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link d-flex align-items-center gap-4 gap-lg-2"
            href="https://github.com/youzarsiph/django-short-links.git">
            <i class="bi bi-github"></i>
            {% translate 'Github' %}
          </a>
        </li>
        <li class="nav-item">
          {% if request.user.is_authenticated %}
          <a class="nav-link d-flex align-items-center gap-4 gap-lg-2" href="{% url 'logout' %}">
            <i class="bi bi-box-arrow-right"></i>
            {% translate 'Log out' %}
          </a>
          {% else %}
          <a class="nav-link d-flex align-items-center gap-4 gap-lg-2" href="{% url 'login' %}">
            <i class="bi bi-box-arrow-in-right"></i>
            {% translate 'Log in' %}
          </a>
          {% endif %}
        </li>
      </ul>
      {% if request.user.is_authenticated %}
      <ul class="navbar-nav">
        <li>
          <div class="card card-body bg-dark fw-bold rounded-5 text-white py-2 px-3 text-center">
            {{request.user.username|capfirst}}
          </div>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

links/templates/links/components/url.html
{% load i18n %}

<div class="card card-body p-4 rounded-4 border-0">
  <div class="d-flex flex-row align-items-center justify-content-between mb-4">
    <h3 class="mb-0">Link #{{ forloop.counter }}</h3>
    <div class="dropdown">
      <a href="#" class="btn btn-sm btn-light rounded-3" data-bs-toggle="dropdown">
        <i class="bi bi-three-dots"></i>
      </a>
      <ul class="dropdown-menu rounded-3 border-0 shadow-sm">
        <li>
          <h4 class="dropdown-header mb-0">
            {% translate 'Options' %}
          </h4>
        </li>
        <li>
          <a href="{% url 'links:redirect' url.token %}" target="_blank"
            class="dropdown-item d-flex flex-row align-items-center gap-4">
            <i class="bi bi-box-arrow-up-right"></i>
            <span class="dropdown-item-text">
              {% translate 'Click' %}
            </span>
          </a>
        </li>
        <li>
          <a href="{% url 'links:url_detail' url.id %}" class="dropdown-item d-flex flex-row align-items-center gap-4">
            <i class="bi bi-info-lg"></i>
            <span class="dropdown-item-text">
              {% translate 'Details' %}
            </span>
          </a>
        </li>
        <li>
          <a href="{% url 'links:update_url' url.id %}" class="dropdown-item d-flex flex-row align-items-center gap-4">
            <i class="bi bi-pencil"></i>
            <span class="dropdown-item-text">
              {% translate 'Edit link' %}
            </span>
          </a>
        </li>
        <li>
          <a href="#" data-bs-toggle="modal" data-bs-target="#deleteModal" onclick="onClick('{{ url.id }}')"
            class="dropdown-item d-flex flex-row align-items-center gap-4">
            <i class="bi bi-trash"></i>
            <span class="dropdown-item-text">
              {% translate 'Delete link' %}
            </span>
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="card-txt mb-4">
    <p class="lead">{{ url.url }}</p>
    <ul class="list-unstyled">
      <li>
        <small class="text-muted">
          {% translate 'Clicks: ' %} {{ url.clicks }}
        </small>
      </li>
      <li>
        <small class="text-muted">
          {% translate 'Created: ' %} {{ url.created_at }}
        </small>
      </li>
      <li>
        <small class="text-muted">
          {% translate 'Last update: ' %} {{ url.updated_at }}
        </small>
      </li>
    </ul>
  </div>
  <div class="card card-body p-4 rounded-4 justify-content-between gap-4 bg-light border-0 overflow-x-auto">
    <p class="mb-0">{{ site_url }}{% url 'links:redirect' url.token %}</p>
    <button id="copy-btn-{{ url.id }}" type="button" onclick="inform('copy-btn-{{ url.id }}')"
      class="btn btn-outline-dark shadow-sm rounded-3 fw-bold"
      data-clipboard-text="{{ site_url }}{% url 'links:redirect' url.token %}">
      <i class="bi bi-clipboard me-3"></i>
      {% translate 'Copy' %}
    </button>
  </div>
</div>

links/templates/links/create.html
{% extends 'links/index.html' %}
{% load i18n %}
{% block title %}{% translate 'Links | Create Link' %}{% endblock %}
{% block content %}
<div class="card card-body p-4 rounded-4 border-0">
  <h2 class="mb-4">
    {% translate 'Create Link' %}
  </h2>
  {% if form.errors %}
  <div class="alert alert-danger rounded-4 shadow-sm" role="alert">
    <div class="badge bg-danger">{% translate 'Error' %}</div>
    {{ form.errors }}
  </div>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <div class="form-floating mb-4">
      {{ form.url }}
      {{ form.url.label_tag }}
      <small class="text-muted">
        {{ form.url.help_text }}
      </small>
    </div>

    <button type="submit" class="btn btn-lg btn-dark w-100 shadow-sm rounded-3 fw-bold">
      {% translate 'Create' %}
    </button>
  </form>
</div>
{% endblock %}
{% block footer %}
<script>
  document.querySelectorAll('label').forEach(i => i.classList.add('form-label'))
  document.querySelectorAll('input').forEach(i => i.classList.add('form-control'))
</script>
{% endblock %}

links/templates/links/delete.html
{% extends 'links/index.html' %}
{% load i18n %}
{% block title %}{% translate 'Links | Delete Link' %}{% endblock %}
{% block content %}
<div class="card card-body p-4 rounded-4 border-0">
  <h2 class="mb-4">
    {% translate 'Delete Link' %}
  </h2>
  <p class="lead mb-4">{{ url.url }}</p>
  <p class="lead mb-4">
    {% translate 'Are you sure you want to delete this link?' %}
  </p>
  {% if form.errors %}
  <div class="alert alert-danger rounded-4 shadow-sm" role="alert">
    <div class="badge bg-danger">{% translate 'Error' %}</div>
    {{ form.errors }}
  </div>
  {% endif %}
  <form method="post">
    {% csrf_token %}

    <div class="d-flex flex-column flex-lg-row align-items-center gap-4">
      <button type="submit" class="btn btn-lg btn-danger w-100 shadow-sm rounded-3 fw-bold">
        {% translate 'Delete' %}
      </button>
      <a href="{% url 'links:url_detail' url.id %}" class="btn btn-lg btn-light w-100 shadow-sm rounded-3 fw-bold">
        {% translate 'Cancel' %}
      </a>
    </div>
  </form>
</div>
{% endblock %}

links/templates/links/detail.html
{% extends 'links/index.html' %}
{% load i18n %}
{% block title %}{% translate 'Links | URL details' %}{% endblock %}
{% block content %}
<h2 class="mb-4">
  {% translate 'Link Details' %}
</h2>
<div class="card card-body p-4 rounded-4 border-0">
  <h3 class="card-title mb-4">{{ url.url }}</h3>
  <div class="card card-body p-4 rounded-4 justify-content-between gap-4 bg-light border-0 mb-4 overflow-x-auto">
    <p class="mb-0">{{ site_url }}{% url 'links:redirect' url.token %}</p>
    <button id="copy-btn" type="button" onclick="inform()" class="btn btn-outline-dark shadow-sm rounded-3 fw-bold"
      data-clipboard-text="{{ site_url }}{% url 'links:redirect' url.token %}">
      <i class="bi bi-clipboard me-3"></i>
      {% translate 'Copy' %}
    </button>
  </div>
  <ul class="list-unstyled mb-4">
    <li>
      <small class="text-muted">
        {% translate 'Clicks: ' %} {{ url.clicks }}
      </small>
    </li>
    <li>
      <small class="text-muted">
        {% translate 'Created: ' %} {{ url.created_at }}
      </small>
    </li>
    <li>
      <small class="text-muted">
        {% translate 'Last update: ' %} {{ url.updated_at }}
      </small>
    </li>
  </ul>
  <div class="d-grid d-md-flex align-items-center justify-content-lg-around gap-4">
    <a class="btn btn-lg btn-success w-100 shadow-sm rounded-3 fw-bold" target="_blank"
      href="{% url 'links:redirect' url.token %}">
      <i class="bi bi-check-lg me-3"></i>
      {% translate 'Verify' %}
    </a>
    {% if request.user == url.user %}
    <a class="btn btn-lg btn-light w-100 shadow-sm rounded-3 fw-bold" href="{% url 'links:update_url' url.id %}">
      <i class="bi bi-pencil me-3"></i>
      {% translate 'Change token' %}
    </a>
    <button class="btn btn-lg btn-danger w-100 shadow-sm rounded-3 fw-bold" data-bs-toggle="modal"
      data-bs-target="#deleteModal" onclick="onClick('{{ url.id }}')">
      <i class="bi bi-trash me-3"></i>
      {% translate 'Delete' %}
    </button>
    {% endif %}
  </div>
</div>

{% include 'links/components/delete-modal.html' %}
{% endblock %}
{% block footer %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.11/clipboard.min.js"
  integrity="sha512-7O5pXpc0oCRrxk8RUfDYFgn0nO1t+jLuIOQdOMRp4APB7uZ4vSjspzp5y6YDtDs4VzUSTbWzBFZ/LKJhnyFOKw=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
  const copyBtn = new ClipboardJS('#copy-btn')

  const btn = document.getElementById('copy-btn')

  const inform = () => {
    btn.innerHTML = '<i class="bi bi-clipboard-check-fill me-3 text-success"></i> <span class="text-success">Copied</span>'

    setTimeout(() => {
      btn.innerHTML = '<i class="bi bi-clipboard me-3"></i> Copy'
    }, 2000);
  }

  const onClick = (id) => {
    const form = document.getElementById('deleteForm')
    form.setAttribute('action', form.getAttribute('action').replace(form.getAttribute('data-last-id'), id))
    form.setAttribute('data-last-id', id)
  }
</script>
{% endblock %}

links/templates/links/index.html
{% extends 'links/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Links | Link shortener' %}{% endblock %}
{% block body_attrs %}class="bg-light"{% endblock %}
{% block header %}
{% include 'links/components/navbar.html' %}
{% endblock %}
{% block main %}
<div class="container d-flex align-items-center justify-content-between">
  <div class="w-100 py-5">
    {% if messages %}
    {% include 'links/components/messages.html' %}
    {% endif %}

    {% block content %}
    <h1 class="display-1">
      <strong>{% translate 'Links' %}</strong>
    </h1>
    <p class="lead mb-4">
      {% blocktranslate %}
      An app that allows users to shorten long urls.
      {% endblocktranslate %}
    </p>
    <section class="row g-4">
      <div class="col-12 col-md-6 col-lg-4">
        <div class="card card-body p-4 rounded-4 border-0">
          <h2 class="mb-4">
            {% translate 'Open Source' %}
          </h2>
          <p class="lead mb-4">
            {% blocktranslate %}
            Links is an open source fast, scalable, secure web app built using Python and Django.
            {% endblocktranslate %}
          </p>
          <a class="btn btn-lg btn-dark w-100 shadow-sm rounded-3 fw-bold"
            href="https://github.com/youzarsiph/django-short-links.git">
            <i class="bi bi-github me-3"></i>
            {% translate 'Github' %}
          </a>
        </div>
      </div>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="card card-body p-4 rounded-4 border-0">
          <h2 class="mb-4">
            {% translate 'Link Management' %}
          </h2>
          <p class="lead mb-4">
            {% blocktranslate %}
            Links allows you to manage your shortened links and track performance.
            {% endblocktranslate %}
          </p>
          <a class="btn btn-lg btn-dark w-100 shadow-sm rounded-3 fw-bold" href="{% url 'links:url_list' %}">
            <i class="bi bi-eye me-3"></i>
            {% translate 'View' %}
          </a>
        </div>
      </div>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="card card-body p-4 rounded-4 border-0">
          <h2 class="mb-4">
            {% translate 'Give it a try' %}
          </h2>
          <form method="post" action="{% url 'links:create_url' %}">
            {% csrf_token %}
            <div class="form-floating mb-4">
              <input type="url" name="url" maxlength="200" required id="id_url" placeholder="{% translate 'Link' %}"
                class="form-control" value="{{ url.value }}">
              <label for="id_url" class="form-label">
                {% translate 'Link' %}
              </label>
              <small class="text-muted">
                {% translate 'The link to be shortened' %}
              </small>
            </div>
            <button type="submit" class="btn btn-lg btn-dark w-100 shadow-sm rounded-3 fw-bold">
              <i class="bi bi-scissors me-3"></i>
              {% translate 'Submit' %}
            </button>
          </form>
        </div>
      </div>
    </section>
    {% endblock %}
  </div>
</div>
{% endblock %}

links/templates/links/list.html
{% extends 'links/index.html' %}
{% load i18n %}
{% block title %}{% translate 'Links | My links' %}{% endblock %}
{% block body_attrs %}class="bg-light"{% endblock %}
{% block container_height %}{% endblock %}
{% block content %}
<h2 class="mb-4">
  {% translate 'My Links' %}
</h2>
<div class="d-flex align-items-lg-center justify-content-between gap-4 flex-column flex-lg-row mb-4">
  <p class="lead mb-0">
    {% translate 'Your shortened links will appear here.' %}
  </p>
  <a href="{% url 'links:create_url' %}" class="btn btn-lg btn-dark shadow-sm rounded-3 fw-bold">
    {% translate 'Add link' %}
  </a>
</div>
<section class="row g-4">
  {% for url in url_list %}
  <div class="col-12 col-md-6 col-lg-4">
    {% include 'links/components/url.html' %}
  </div>
  {% empty %}
  <div class="col-12">
    <div class="card card-body p-4 rounded-4 border-0">
      <h3 class="card-title mb-4">No shortened links!</h3>
      <div class="card-text">
        <p class="lead mb-4">{% translate 'It looks like you do not have any links.' %}</p>
        <a href="{% url 'links:create_url' %}" class="btn btn-lg btn-dark w-100 shadow-sm rounded-3 fw-bold">
          {% translate 'Add link' %}
        </a>
      </div>
    </div>
  </div>
  {% endfor %}
</section>

{% include 'links/components/delete-modal.html' %}
{% endblock %}
{% block footer %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.11/clipboard.min.js"
  integrity="sha512-7O5pXpc0oCRrxk8RUfDYFgn0nO1t+jLuIOQdOMRp4APB7uZ4vSjspzp5y6YDtDs4VzUSTbWzBFZ/LKJhnyFOKw=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
  const inform = (id) => {
    const copyBtn = new ClipboardJS(`#${id}`)

    const btn = document.getElementById(id)
    btn.innerHTML = '<i class="bi bi-clipboard-check-fill me-3 text-success"></i> <span class="text-success">Copied</span>'

    setTimeout(() => {
      btn.innerHTML = '<i class="bi bi-clipboard me-3"></i> Copy'
    }, 2000);
  }

  const onClick = (id) => {
    const form = document.getElementById('deleteForm')
    form.setAttribute('action', form.getAttribute('action').replace(form.getAttribute('data-last-id'), id))
    form.setAttribute('data-last-id', id)
  }
</script>
{% endblock %}

links/templates/links/update.html
{% extends 'links/index.html' %}
{% load i18n %}
{% block title %}{% translate 'Links | Update Link' %}{% endblock %}
{% block content %}
<div class="card card-body p-4 rounded-4 border-0">
  <h2 class="mb-4">
    {% translate 'Update Link' %}
  </h2>
  <p class="lead mb-4">{{ url.url }}</p>
  {% if form.errors %}
  <div class="alert alert-danger rounded-4 shadow-sm" role="alert">
    <div class="badge bg-danger">{% translate 'Error' %}</div>
    {{ form.errors }}
  </div>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <div class="form-floating mb-4">
      {{ form.token }}
      {{ form.token.label_tag }}
      <small class="text-muted">
        {{ form.token.help_text }}
      </small>
    </div>
    <div class="form-floating mb-4">
      {{ form.url }}
      {{ form.url.label_tag }}
      <small class="text-muted">
        {{ form.url.help_text }}
      </small>
    </div>

    <button type="submit" class="btn btn-lg btn-dark w-100 shadow-sm rounded-3 fw-bold">
      {% translate 'Update' %}
    </button>
  </form>
</div>
{% endblock %}
{% block footer %}
<script>
  document.querySelectorAll('label').forEach(i => i.classList.add('form-label'))
  document.querySelectorAll('input').forEach(i => i.classList.add('form-control'))
</script>
{% endblock %}